services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    env_file:
      - ./env_files/mongo.env
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8091:8081
    env_file:
      - ./env_files/mongo.env
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "google_pse"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
    env_file:
      - ./env_files/openwebui.env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  ollama:
    volumes:
      - ollama:/root/.ollama
      - ./scripts/ollama_entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    ports:
      - 11434:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  mongodb_data:
  open-webui:
  ollama:
